#pragma once

#define MINUTE_TO_MS 60000
#define TIMEOUT 5 * MINUTE_TO_MS

#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS

#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#undef ENCODER_A_PINS_RIGHT
#undef ENCODER_B_PINS_RIGHT
#define ENCODER_A_PINS { B6 }
#define ENCODER_B_PINS { B2 }
#define ENCODER_A_PINS_RIGHT { B2 }
#define ENCODER_B_PINS_RIGHT { B6 }

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_TIMEOUT TIMEOUT
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_WPM_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#define OLED_TIMEOUT TIMEOUT
#define OLED_BRIGHTNESS 50

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_WHEEL_DELAY 0

// #define MK_3_SPEED // Constant speed mouse movement

// Ocean Dream
#define ENABLE_MOON // Uses 182 bytes
#define ENABLE_WAVE // Uses 844 bytes
#define ENABLE_SHOOTING_STARS // Uses 872 bytes
#define ENABLE_ISLAND
#define ENABLE_STARS // Uses 606 bytes
