#pragma once

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_KEYPRESSES
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RIVERFLOW
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#undef ENCODER_A_PINS_RIGHT
#undef ENCODER_B_PINS_RIGHT

#define ENCODER_A_PINS { B6 }
#define ENCODER_B_PINS { B2 }
#define ENCODER_A_PINS_RIGHT { B2 }
#define ENCODER_B_PINS_RIGHT { B6 }

#undef OLED_TIMEOUT
#define MINUTE_TO_MS 60000
#define OLED_SCREENSAVER_TIMEOUT 1 * MINUTE_TO_MS
#define OLED_TIMEOUT 5 * MINUTE_TO_MS
