#pragma once

#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS

#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_TIMEOUT 120000
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_WPM_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE

#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#define OLED_TIMEOUT 120000
#define OLED_BRIGHTNESS 50

#define MK_3_SPEED // Constant speed

#define ENABLE_MOON // Uses 182 bytes
#define ENABLE_WAVE // Uses 844 bytes
#define ENABLE_SHOOTING_STARS // Uses 872 bytes
#define ENABLE_ISLAND
#define ENABLE_STARS // Uses 606 bytes
